container:
  image: openjdk:11-jdk
  cpu: 2
  memory: 1G


task:
  clone_script: |
    if [[ -z "$CIRRUS_PR" ]]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi
    git clone https://github.com/watchdog-wms/build-tools
    WATCHDOG_PR_CHECKER=$(pwd)/build-tools/jars/PullRequestChecker.jar
    ls "${WATCHDOG_PR_CHECKER}" > /dev/null 2>&1

task:
  name: signed commit test
  script: 
    - env
    - ls -la .
    - java -jar "${WATCHDOG_PR_CHECKER}" -check "VERIFIED_COMMIT"
